IGNORE_REGEX = r'[^a-z0-9\s\-\'\(\)\,]'

REPLACEMENTS = {
    "blue violet": [r"blueviolet"],
    "dark magenta": [r"darkmagenta"],
    "dark slate": [r"darkslategray"],
    "dark violet": [r"darkviolet"],
    "green yellow": [r"greenyellow"],
    "honeydew": [r"honeydydew"],
    "light coral": [r"lightcoral"],
    "lime green": [r"limegreen"],
    "medium purple": [r"mediumpurple"],
    "medium sea green": [r"mediumseagreen"],
    "medium spring green": [r"mediumspringgreen"],
    "orange red": [r"orangered"],
    "sea green": [r"seagreen"],
    "yellow green": [r"yellowgreen"],

    # reformatted/slightly modified from MLMC (processing_scripts/01_data_cleaning/lang_rules/en_rules.js)
    "avocado": [r"avacado"],
    "beige": [r"^bage$",r"baige",r"biege"],
    "blue": [r"^blu$",r"^bluw$",r"^bue$"],
    "burgundy": [r"burgendy",r"burgandy"],
    "cerulean": [r"cerulian"],
    "chartreuse": [r"chartruse",r"chartruese",r"charteuse",r"chartruce",r"chatreuse"],
    "cobalt": [r"colbalt",r"cobolt"],
    'cyan': [r"^cian$"],
    "forest": [r"forrest"],
    "fuchsia": [r"fusha",r"fuchia",r"fucsia",r"fusia",r"fushia",r"fuschia",r"fuscia",r"fuscia",r"fascia",r"fucia",r"fucia",r"fucshia",r"fuscha",r"fuschsia",r"fushchia",r"fushcia",r"fusica"],
    "green": [r"^geen$",r"^grean$",r"^gree$",r"^greeb$",r"^greeen$",r"^gren$",r"^grren$",r"^gteen$"],
    "lavender": [r"lavendar",r"lavander"],
    "lime green": [r"^linegreen"],
    "magenta": [r"majenta"],
    "maroon": [r"marron",r"marroon"],
    "mauve": [r"muave"],
    "indigo": [r"indago",r"indego",r"indgo"],
    "idk": [r"i dont know",r"i don't know",r"dont know"],
    "khaki": [r"kahki",r"kaki"],
    "light green": [r"light gree$"],
    "magenta": [r"magentia",r"magento",r"magnenta",r"magneta",r"mangenta",r"megenta"],
    "mahogany": [r"mahagony"],
    "maroon": [r"maron$",r"maroom",r"maroone"],
    "ochre": [r"^ocre$"],
    "orange": [r"^orage$",r"^oragne$",r"^orance$",r"^orane$",r"^orang$",r"^orangw$",r"^organe$",r"^organge$",r"^ornage$"],
    "periwinkle": [r"perrywinkle",r"perriwinkle"],
    "pink": [r"^pank$",r"^pinl$"],
    "purple": [r"puple",r"pruple",r"^pirple$",r"^pueple$",r"purpel",r"purpl$",r"purplr",r"putple"],
    "puce": [r"^puse$"],
    "red": [r"^ref$",r"^res$"],
    "reddish": [r"redish"],
    "robin egg": [r"robinsegg"],
    "royal blue": [r"royal blye"],
    "scarlet": [r"scarlett"],
    "sienna": [r"siena"],
    "teal": [r"^teel$",r"^teil$"],
    "terracotta": [r"terracota",r"terra cotta"],
    "turquoise": [r"turquise",r"turqouise",r"turquise",r"turquiose",r"torquoise",r"turqoise",r"terquoise",r"torquise",r"torquois$",r"torquose",r"tourquise",r"tourquoise",r"tuqoise",r"tuquoise",r"turcoise",r"turqouis",r"turquois$",r"turquoises"],
    "viloet": [r"viloet"],
    "yellow": [r"yello$",r"yelloe",r"yelloq",r"yelow"],
}